name: ex00
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^5.0.3
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^25.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
